#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /api/login_check

offers:
  resource: App\Controller\OfferController
  prefix: api

register:
  path: /register
  controller: App\Controller\SecurityController:register