#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /api/login_check

notices:
  resource: App\Controller\NoticeController
  prefix: api

#register:
#  path: /api/register
#  controller: App\Controller\SecurityController:register
